"""DPTiny: a minimal educational deep-learning framework."""

from dptiny import data, nn, optim
from dptiny.backend import (
    get_array_module,
    is_available,
    is_gpu,
    to_cpu,
    to_gpu,
    use_cpu,
    use_gpu,
    xp,
)
from dptiny.core import (
    Config,
    Function,
    Parameter,
    Variable,
    as_array,
    as_variable,
    no_grad,
    test_mode,
    using_config,
)
from dptiny.data import DataLoader, get_fashion_mnist, get_mnist
from dptiny.functions import (
    accuracy,
    add,
    avg_pool2d,
    batch_norm,
    broadcast_to,
    conv2d,
    div,
    dropout,
    exp,
    flatten,
    get_item,
    linear,
    log,
    matmul,
    max,
    max_pool2d,
    mean,
    mean_squared_error,
    mul,
    neg,
    pow,
    rdiv,
    relu,
    reshape,
    rsub,
    sigmoid,
    softmax,
    softmax_cross_entropy,
    sub,
    sum,
    sum_to,
    tanh,
    transpose,
)
from dptiny.nn import Conv2d, Linear, MLP
from dptiny.optim import SGD, Adam

__version__ = "0.2.0"

__all__ = [
    "Adam",
    "Config",
    "Conv2d",
    "DataLoader",
    "Function",
    "Linear",
    "MLP",
    "Parameter",
    "SGD",
    "Variable",
    "accuracy",
    "add",
    "as_array",
    "as_variable",
    "avg_pool2d",
    "batch_norm",
    "broadcast_to",
    "conv2d",
    "data",
    "div",
    "dropout",
    "exp",
    "flatten",
    "get_array_module",
    "get_item",
    "get_mnist",
    "get_fashion_mnist",
    "is_available",
    "is_gpu",
    "linear",
    "log",
    "matmul",
    "max",
    "max_pool2d",
    "mean",
    "mean_squared_error",
    "mul",
    "neg",
    "nn",
    "no_grad",
    "optim",
    "pow",
    "rdiv",
    "relu",
    "reshape",
    "rsub",
    "sigmoid",
    "softmax",
    "softmax_cross_entropy",
    "sub",
    "sum",
    "sum_to",
    "tanh",
    "test_mode",
    "to_cpu",
    "to_gpu",
    "transpose",
    "use_cpu",
    "use_gpu",
    "using_config",
    "xp",
]
